/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.parkingsystem.view.vehiculo;
import com.parkingsystem.controller.DetalleVehiculoController;


/**
 *
 * @author David
 */
public class DetalleVehiculoVista extends javax.swing.JFrame {

    private DetalleVehiculoController detalleVehiculoController;
    
    public DetalleVehiculoVista(int idVehiculo) {
        initComponents();
        inicializarControlador();
        detalleVehiculoController.listarDetalleVehiculo(idVehiculo);
    }

    private void inicializarControlador() {
        detalleVehiculoController = new DetalleVehiculoController(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtConductorNombre = new javax.swing.JLabel();
        txtDNI = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        ticketContainer = new javax.swing.JPanel();
        txtTicket1 = new javax.swing.JLabel();
        txtTicket2 = new javax.swing.JLabel();
        txtTicket3 = new javax.swing.JLabel();
        txtTicket4 = new javax.swing.JLabel();
        txtTicket5 = new javax.swing.JLabel();
        txtTicketEstatus = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JLabel();
        txtZona = new javax.swing.JLabel();
        txtPiso = new javax.swing.JLabel();
        abonadoContainer = new javax.swing.JPanel();
        txtAbo1 = new javax.swing.JLabel();
        txtAbo2 = new javax.swing.JLabel();
        txtAbo3 = new javax.swing.JLabel();
        txtAbo4 = new javax.swing.JLabel();
        txtAbo5 = new javax.swing.JLabel();
        txtFechaInicioAbonado = new javax.swing.JLabel();
        txtFechaFinAbonado = new javax.swing.JLabel();
        txtTipoAbono = new javax.swing.JLabel();
        txtMontoAbonado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 1050, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Datos del Vehiculo");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Placa:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Datos del Conductor");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Conductor:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Color:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Marca:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("DNI:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Teléfono:");

        txtColor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtColor.setText(" ");

        txtPlaca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPlaca.setText(" ");

        txtMarca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMarca.setText(" ");

        txtConductorNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConductorNombre.setText(" ");

        txtDNI.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDNI.setText(" ");

        txtTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTelefono.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConductorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtColor)
                    .addComponent(txtMarca)
                    .addComponent(txtPlaca))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtConductorNombre)
                    .addComponent(txtDNI)
                    .addComponent(txtTelefono))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 190));

        ticketContainer.setBackground(new java.awt.Color(255, 255, 255));
        ticketContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticketContainer.setPreferredSize(new java.awt.Dimension(433, 185));

        txtTicket1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtTicket1.setText("Automovil Actualmente:");

        txtTicket2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtTicket2.setText("Datos del Estacionamiento");

        txtTicket3.setText("Fecha de entrada:");

        txtTicket4.setText("Zona:");

        txtTicket5.setText("Piso:");

        txtTicketEstatus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtTicketEstatus.setText(" ");

        txtFechaEntrada.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFechaEntrada.setText(" ");

        txtZona.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtZona.setText(" ");

        txtPiso.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPiso.setText(" ");

        javax.swing.GroupLayout ticketContainerLayout = new javax.swing.GroupLayout(ticketContainer);
        ticketContainer.setLayout(ticketContainerLayout);
        ticketContainerLayout.setHorizontalGroup(
            ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketContainerLayout.createSequentialGroup()
                        .addGroup(ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTicket2)
                            .addGroup(ticketContainerLayout.createSequentialGroup()
                                .addComponent(txtTicket1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTicketEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ticketContainerLayout.createSequentialGroup()
                                .addComponent(txtTicket5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(ticketContainerLayout.createSequentialGroup()
                        .addComponent(txtTicket3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTicket4)
                        .addGap(18, 18, 18)
                        .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        ticketContainerLayout.setVerticalGroup(
            ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTicket1)
                    .addComponent(txtTicketEstatus))
                .addGap(18, 18, 18)
                .addComponent(txtTicket2)
                .addGap(18, 18, 18)
                .addGroup(ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTicket3)
                    .addComponent(txtTicket4)
                    .addComponent(txtFechaEntrada)
                    .addComponent(txtZona))
                .addGap(18, 18, 18)
                .addGroup(ticketContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTicket5)
                    .addComponent(txtPiso))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.add(ticketContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, 190));

        abonadoContainer.setBackground(new java.awt.Color(255, 255, 255));
        abonadoContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAbo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtAbo1.setText("Datos de abonado");

        txtAbo2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAbo2.setText("Fecha de inicio:");

        txtAbo3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAbo3.setText("Fecha de FIn:");

        txtAbo4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAbo4.setText("Tipo de abono:");

        txtAbo5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAbo5.setText("Monto:");

        txtFechaInicioAbonado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFechaInicioAbonado.setText(" ");

        txtFechaFinAbonado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFechaFinAbonado.setText(" ");

        txtTipoAbono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTipoAbono.setText(" ");

        txtMontoAbonado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMontoAbonado.setText(" ");

        javax.swing.GroupLayout abonadoContainerLayout = new javax.swing.GroupLayout(abonadoContainer);
        abonadoContainer.setLayout(abonadoContainerLayout);
        abonadoContainerLayout.setHorizontalGroup(
            abonadoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abonadoContainerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(abonadoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abonadoContainerLayout.createSequentialGroup()
                        .addComponent(txtAbo1)
                        .addContainerGap(903, Short.MAX_VALUE))
                    .addGroup(abonadoContainerLayout.createSequentialGroup()
                        .addComponent(txtAbo2)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaInicioAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAbo3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaFinAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAbo4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(txtAbo5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        abonadoContainerLayout.setVerticalGroup(
            abonadoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abonadoContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtAbo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(abonadoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbo2)
                    .addComponent(txtAbo3)
                    .addComponent(txtAbo4)
                    .addComponent(txtAbo5)
                    .addComponent(txtFechaInicioAbonado)
                    .addComponent(txtFechaFinAbonado)
                    .addComponent(txtTipoAbono)
                    .addComponent(txtMontoAbonado))
                .addGap(19, 19, 19))
        );

        jPanel4.add(abonadoContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 1050, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Consulta detalle de Vehiculo");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 430, -1));

        btnVolver.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/anterior.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel4.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, 120, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleVehiculoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleVehiculoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleVehiculoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleVehiculoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleVehiculoVista(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel abonadoContainer;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel ticketContainer;
    public javax.swing.JLabel txtAbo1;
    public javax.swing.JLabel txtAbo2;
    public javax.swing.JLabel txtAbo3;
    public javax.swing.JLabel txtAbo4;
    public javax.swing.JLabel txtAbo5;
    public javax.swing.JLabel txtColor;
    public javax.swing.JLabel txtConductorNombre;
    public javax.swing.JLabel txtDNI;
    public javax.swing.JLabel txtFechaEntrada;
    public javax.swing.JLabel txtFechaFinAbonado;
    public javax.swing.JLabel txtFechaInicioAbonado;
    public javax.swing.JLabel txtMarca;
    public javax.swing.JLabel txtMontoAbonado;
    public javax.swing.JLabel txtPiso;
    public javax.swing.JLabel txtPlaca;
    public javax.swing.JLabel txtTelefono;
    public javax.swing.JLabel txtTicket1;
    public javax.swing.JLabel txtTicket2;
    public javax.swing.JLabel txtTicket3;
    public javax.swing.JLabel txtTicket4;
    public javax.swing.JLabel txtTicket5;
    public javax.swing.JLabel txtTicketEstatus;
    public javax.swing.JLabel txtTipoAbono;
    public javax.swing.JLabel txtZona;
    // End of variables declaration//GEN-END:variables
}
